##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## Dart/Flutter (DF) Packages by DevCetra.com & contributors. Use of this
## source code is governed by an MIT-style license that can be found in the
## LICENSE file.
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: df_gps_math
description: A package that provides some math functions for global (GPS) positions.
version: 0.1.3
repository: https://github.com/robmllze/df_gps_math

## -----------------------------------------------------------------------------

environment:
  sdk: ">=3.5.0 <4.0.0"

## -----------------------------------------------------------------------------

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
