##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## Dart/Flutter (DF) Packages by DevCetra.com & contributors. ee MIT LICENSE
## file in the root directory.
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: df_gps_math
description: A package that provides some math functions for global (GPS) positions.
version: 0.1.1
repository: https://github.com/robmllze/df_gps_math

## -----------------------------------------------------------------------------

environment:
  sdk: ">=3.0.0 < 4.0.0"

## -----------------------------------------------------------------------------

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
